import re

VOUCHER_BRANDS = [
  "@Home", "Absolute Barbecues", "Air India", "Ajio", "Aldo", "Aliste", "Allen Solly", "Amazon", 
  "Amazon Fresh", "Amazon Prime Lite", "Amazon Prime Membership", "Amazon Prime Shopping", 
  "Amazon Shopping", "American Eagle", "American Tourister", "AND", "Anita Dongre", 
  "Apollo Pharmacy", "Archies", "Armani Exchange", "Arrow", "Asia Seven Express", "Assembly", 
  "Aurelia", "Barbeque Nation", "Bare Anatomy", "Baskin Robbins", "Bata", "Bath and Body Works", 
  "Behrouz Biryani", "Beverly Hills Polo Club", "Bewakoof", "Beyoung", "Bhima Jewellers", 
  "Bhima Jewellers - Gold Jewellery", "Biba (Online)", "Big Basket", "Bikanervala", "Blackberrys", 
  "Blaupunkt", "Blinkit", "Blissclub", "Blue Tokai", "Bluestone", "Bobbi Brown", "Body Craft", 
  "Bombay Shaving", "Book My Show", "Cafe Coffee Day", "Cafe Delhi Heights", "Call it Spring", 
  "Campus", "Campus Sutra", "Cello", "Charles and Keith", "Chemist at Play", "Chumbak", 
  "Cleartrip", "Cleartrip Hotels", "Coach", "ColorPlus", "Costa Coffee", "Croma", "Cult", 
  "Decathlon Omni", "Decathlon Sports India", "Discovery Plus", "District", "Dominos", 
  "Donatekart", "Dune London", "EaseMyTrip", "Easy Buy", "EatSure", "Euphoria", 
  "Euphoria Gold Coin", "Fab Hotels", "Fabindia", "Fastrack", "Ferns N Petals", "First Cry", 
  "Fitpass", "Flipkart", "Flower Aura", "Forever New", "Forever21", "Foxtale", "Freecultr", 
  "Fresh Menu", "Future World", "Gaana", "Giva Gold Jewellery", "Giva Silver Jewellery", 
  "GRT", "G-Star Raw", "Gupta Distributors", "Hamleys", "Health and Glow", "Helios", "HiDesign", 
  "Himalaya", "Hindustan Times Premium", "Hoichoi", "Home Centre", "Home Stop", "HPCL", 
  "Hugo Boss", "Hush Puppies", "IKEA", "Imagine Apple Premium Reseller", "Indian Terrrain", 
  "Inglot", "ITC Hotels", "ixigo", "Jack & Jones", "Jimmy Choo", "Jio Mart", "JioHotstar", 
  "Jockey", "Jos Alukkas Gold Jewellery", "Joyalukkas Diamond & Platinum", "Joyalukkas Gold Jewellery", 
  "Kalyan Jewellers Diamond Jewellery", "Kalyan Jewellers Gold Jewellery", "Kalyan jewellery", 
  "Kama Ayurveda", "Kate Spade", "KFC", "Lakme Salon", "Lawrence And Mayo", "Lee", "Lenskart", 
  "Levis", "Lifestyle", "Linen Club", "Lite Bite Foods", "Live Hindustan", "Louis Philippe", 
  "Luxe", "Mac", "Machaan", "Mainland China", "Make My Trip", "MakeMyTrip Holiday", 
  "MakeMyTrip Hotels", "Mamaearth", "Marks & Spencer", "Marriott", "Marriott Hotels", 
  "Marriott Spa", "Max Fashion", "McDonalds", "Mediwheel", "Mia By Tanishq", "Michael Kors", 
  "MiniKlub", "More", "Mother care", "My Jio Store", "Myntra", "Nature's Basket", "Netmeds", 
  "Nykaa", "Nykaa Man", "O2 Spa", "Oh! Calcutta", "OLA Cabs", "Organic India", "Ornaz", 
  "OTTPlay", "Ovenstory", "Pantaloons", "Park Avenue", "Parx", "Pepperfry", "Peter England", 
  "Pizza Hut", "Planet Fashion", "Points for Good", "Polar Bear", "Prestige", 
  "Prestige Smart Kitchen", "Puma", "Punjab Grill", "PVR Cinemas", "R&B", "Rangriti", 
  "Ratnadeep Super Market", "Ray Ban", "Relaxo", "Reliance Digital", "Reliance Footwear", 
  "Reliance Jewels", "Reliance Smart", "Reliance Smart Bazaar", "Reliance Smart Point", 
  "Reliance Trends", "Reliance-Fashion Factory", "Resonate", "Samsonite", "Satya Paul", 
  "Scotch & Soda", "Shell", "Shiva Organic", "Shoppers Stop", "Sigree", "Simon Carter", 
  "Simple", "Skechers", "Skullcandy", "Smile Foundation", "Sony Liv", "Speedo", "Spencer's", 
  "Starbucks", "Sterling Holidays", "Steve Madden", "Street Foods By Punjab Grill", "Subway", 
  "Sunscoop", "SUPA", "Superdry", "Sweet Bengal", "Swiggy", "Taj Hotels", "Taneira", 
  "Tanishq Gold Jewellery", "Tanishq Studded", "Tata Cliq", "Tata CliQ Luxury", "Tego", 
  "TGIF", "The Body Shop", "The Raymond Shop", "Timezone", "Titan", "Toscano", 
  "Trends Footwear", "Trends Junior", "Trends Man", "Trends Women", "Truefitt & Hill", "Tumi", 
  "Uber", "Unlimited", "Urban Ladder", "USPA", "Van Heusen", "Vero Moda", "Victoria's Secret", 
  "Vijay Sales", "V-Mart", "W For Women", "Wakefit", "Westside", "Wildcraft", "William Penn", 
  "Woggles", "Wonderchef", "Woodland", "Wow Momo", "Wow!Chicken", "Wow!China", "Wrangler", 
  "Yatra", "YouMee", "Zee5", "Zepto", "Zomato"
]

def guess_domain(brand):
    # Some hardcoded famous ones
    mapping = {
        "amazon": "amazon.in",
        "amazon fresh": "amazon.in",
        "amazon prime lite": "amazon.in",
        "amazon prime membership": "amazon.in",
        "amazon prime shopping": "amazon.in",
        "amazon shopping": "amazon.in",
        "flipkart": "flipkart.com",
        "zomato": "zomato.com",
        "swiggy": "swiggy.com",
        "myntra": "myntra.com",
        "nykaa": "nykaa.com",
        "nykaa man": "nykaa.com",
        "big basket": "bigbasket.com",
        "blinkit": "blinkit.com",
        "zepto": "zepto.in",
        "make my trip": "makemytrip.com",
        "makemytrip holiday": "makemytrip.com",
        "makemytrip hotels": "makemytrip.com",
        "cleartrip": "cleartrip.com",
        "cleartrip hotels": "cleartrip.com",
        "easemytrip": "easemytrip.com",
        "yatra": "yatra.com",
        "book my show": "bookmyshow.com",
        "pvr cinemas": "pvrcinemas.com",
        "starbucks": "starbucks.in",
        "cafe coffee day": "cafecoffeeday.com",
        "dominos": "dominos.co.in",
        "pizza hut": "pizzahut.co.in",
        "kfc": "kfc.co.in",
        "mcdonalds": "mcdonaldsindia.com",
        "baskin robbins": "baskinrobbinsindia.com",
        "bata": "bata.in",
        "lifestyle": "lifestylestores.com",
        "shoppers stop": "shoppersstop.com",
        "pantaloons": "pantaloons.com",
        "max fashion": "maxfashion.in",
        "westside": "westside.com",
        "reliance digital": "reliancedigital.in",
        "croma": "croma.com",
        "tata cliq": "tatacliq.com",
        "tata cliq luxury": "luxury.tatacliq.com",
        "decathlon omni": "decathlon.in",
        "decathlon sports india": "decathlon.in",
        "puma": "puma.com",
        "adidas": "adidas.co.in",
        "nike": "nike.com",
        "levis": "levi.in",
        "kalyan jewellers gold jewellery": "kalyanjewellers.net",
        "kalyan jewellers diamond jewellery": "kalyanjewellers.net",
        "kalyan jewellery": "kalyanjewellers.net",
        "tanishq gold jewellery": "tanishq.co.in",
        "tanishq studded": "tanishq.co.in",
        "mia by tanishq": "miabytanishq.com",
        "joyalukkas diamond & platinum": "joyalukkas.in",
        "joyalukkas gold jewellery": "joyalukkas.in",
        "bhima jewellers": "bhimajewellers.com",
        "bhima jewellers - gold jewellery": "bhimajewellers.com",
        "giva gold jewellery": "giva.co",
        "giva silver jewellery": "giva.co",
        "bluestone": "bluestone.com",
        "himalaya": "himalayawellness.in",
        "the body shop": "thebodyshop.in",
        "bath and body works": "bathandbodyworks.in",
        "kama ayurveda": "kamaayurveda.in",
        "mamaearth": "mamaearth.in",
        "apollo pharmacy": "apollopharmacy.in",
        "netmeds": "netmeds.com",
        "first cry": "firstcry.com",
        "pepperfry": "pepperfry.com",
        "urban ladder": "urbanladder.com",
        "ikea": "ikea.com",
        "ola cabs": "olacabs.com",
        "uber": "uber.com",
        "marriott": "marriott.com",
        "marriott hotels": "marriott.com",
        "taj hotels": "tajhotels.com",
        "itc hotels": "itchotels.com",
        "air india": "airindia.com",
        "sony liv": "sonyliv.com",
        "zee5": "zee5.com",
        "discovery plus": "discoveryplus.in",
    }
    
    clean = brand.lower().strip()
    if clean in mapping:
        return mapping[clean]
        
    # Remove symbols and spaces
    simple = re.sub(r'[^a-z0-9]', '', clean)
    return simple + ".com"

output = "export const VOUCHER_BRANDS = [\n"
for brand in VOUCHER_BRANDS:
    domain = guess_domain(brand)
    output += f"  {{ name: \"{brand}\", domain: \"{domain}\" }},\n"
output += "];\n"

with open("brands_data.ts", "w") as f:
    f.write(output)

print("Created brands_data.ts")
