/** Product records built from supplied catalog photographs. */
export type CatalogSeed = {
  categorySlug: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  bulkPrice: string;
  images: string[];
  features: string[];
};

export const CATALOG_SEED: CatalogSeed[] = [
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-navy-notebook-bottle-set',
    name: 'Navy Notebook and Bottle Set',
    description: 'Gift box with a navy notebook, bottle, pen, and card.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-07.jpg', '/images/catalog/corporate-listing/download-07-alt.jpg'],
    features: ['Rigid gift box', 'Notebook', 'Bottle and pen'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-blue-notebook-bottle-set',
    name: 'Blue Notebook and Bottle Set',
    description: 'Open gift set with a notebook, two bottles, and a pen.',
    price: 2079,
    bulkPrice: 'From ₹1,620/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-08.jpg', '/images/catalog/corporate-listing/download-08-alt.jpg'],
    features: ['Gift box', 'Notebook', 'Two bottles'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-slate-notebook-bottle-box',
    name: 'Slate Notebook and Bottle Box',
    description: 'Black gift box holding a notebook, bottle, and pen.',
    price: 2259,
    bulkPrice: 'From ₹1,760/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-09.jpg', '/images/catalog/corporate-listing/download-09-alt.jpg'],
    features: ['Matte gift box', 'Notebook', 'Bottle'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-navy-desk-gift-set',
    name: 'Navy Desk Gift Set',
    description: 'Navy tray set with notebook, pen, and bottle.',
    price: 2439,
    bulkPrice: 'From ₹1,900/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-10.jpg', '/images/catalog/corporate-listing/download-10-alt.jpg'],
    features: ['Presentation tray', 'Notebook and pen', 'Bottle'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-black-journal-set',
    name: 'Black Journal Set',
    description: 'Black journal, pen, and bottle arranged in a gift box.',
    price: 2619,
    bulkPrice: 'From ₹2,040/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-11.jpg', '/images/catalog/corporate-listing/download-11-alt.jpg'],
    features: ['Journal', 'Pen', 'Bottle'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-slim-notebook-gift-box',
    name: 'Slim Notebook Gift Box',
    description: 'Compact box with a notebook, pen, and slim bottle.',
    price: 2799,
    bulkPrice: 'From ₹2,180/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-12.jpg', '/images/catalog/corporate-listing/download-12-alt.jpg'],
    features: ['Compact box', 'Notebook', 'Slim bottle'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-desk-essentials-gift-set',
    name: 'Desk Essentials Gift Set',
    description: 'Curated set with bottle, notebook, mug, pouch, and keys.',
    price: 2979,
    bulkPrice: 'From ₹2,320/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-13.jpg', '/images/catalog/corporate-listing/download-13-alt.jpg'],
    features: ['Bottle and mug', 'Notebook', 'Pouch'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-beige-notebook-bottle-tray',
    name: 'Beige Notebook and Bottle Tray',
    description: 'Tray presentation with notebook, pen, and bottle.',
    price: 3159,
    bulkPrice: 'From ₹2,460/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-14.jpg', '/images/catalog/corporate-listing/download-14-alt.jpg'],
    features: ['Gift tray', 'Notebook and pen', 'Bottle'],
  },
  {
    categorySlug: 'corporate-hampers',
    slug: 'corporate-hamper-notebook-mug-flask-set',
    name: 'Notebook, Mug and Flask Set',
    description: 'White box with notebook, mug, and flask.',
    price: 3339,
    bulkPrice: 'From ₹2,600/unit (25+ qty)',
    images: ['/images/catalog/corporate-listing/download-15.jpg', '/images/catalog/corporate-listing/download-15-alt.jpg'],
    features: ['White gift box', 'Notebook', 'Mug and flask'],
  },
  {
    categorySlug: 'employee-joining-kits',
    slug: 'joining-kraft-welcome-kit',
    name: 'Kraft Welcome Kit',
    description: 'Kraft box with spiral notebook, glass bottle, and pen.',
    price: 999,
    bulkPrice: 'From ₹780/unit (25+ qty)',
    images: ['/images/catalog/employee-joining/01.jpg', '/images/catalog/employee-joining/01-alt.jpg'],
    features: ['Kraft box', 'Spiral notebook', 'Bottle and pen'],
  },
  {
    categorySlug: 'employee-joining-kits',
    slug: 'joining-navy-welcome-box',
    name: 'Navy Welcome Box',
    description: 'Navy gift box with notebook, pen, and metal bottle.',
    price: 1219,
    bulkPrice: 'From ₹950/unit (25+ qty)',
    images: ['/images/catalog/employee-joining/02.jpg', '/images/catalog/employee-joining/02-alt.jpg'],
    features: ['Navy gift box', 'Notebook and pen', 'Metal bottle'],
  },
  {
    categorySlug: 'employee-joining-kits',
    slug: 'joining-grey-stationery-kit',
    name: 'Grey Stationery Kit',
    description: 'Grey notebook, card holder, pen, and bottle in a tray.',
    price: 1439,
    bulkPrice: 'From ₹1,120/unit (25+ qty)',
    images: ['/images/catalog/employee-joining/03.jpg', '/images/catalog/employee-joining/03-alt.jpg'],
    features: ['Notebook', 'Card holder', 'Bottle'],
  },
  {
    categorySlug: 'employee-joining-kits',
    slug: 'joining-open-box-notebook-kit',
    name: 'Open-Box Notebook Kit',
    description: 'Grey notebook and pen beside an open gift box and bottle.',
    price: 1659,
    bulkPrice: 'From ₹1,290/unit (25+ qty)',
    images: ['/images/catalog/employee-joining/04.jpg', '/images/catalog/employee-joining/04-alt.jpg'],
    features: ['Open gift box', 'Notebook and pen', 'Bottle'],
  },
  {
    categorySlug: 'employee-joining-kits',
    slug: 'joining-desk-welcome-set',
    name: 'Desk Welcome Set',
    description: 'Black notebook, pen, and tall bottle on a wooden desk.',
    price: 1879,
    bulkPrice: 'From ₹1,470/unit (25+ qty)',
    images: ['/images/catalog/employee-joining/05.jpg', '/images/catalog/employee-joining/05-alt.jpg'],
    features: ['Notebook', 'Pen', 'Insulated bottle'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bamboo-bottle-journal-box',
    name: 'Bamboo Bottle and Journal Box',
    description: 'Gift box with bottle, notebook, and bamboo board.',
    price: 449,
    bulkPrice: 'From ₹350/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/01.jpg', '/images/catalog/eco-friendly/01-alt.jpg'],
    features: ['Gift box', 'Bottle', 'Notebook and bamboo board'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-black-journal-bottle-box',
    name: 'Black Journal and Bottle Box',
    description: 'Black gift box with journal, bottle, and pen.',
    price: 539,
    bulkPrice: 'From ₹420/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/02.jpg', '/images/catalog/eco-friendly/02-alt.jpg'],
    features: ['Black box', 'Journal', 'Bottle and pen'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-mug-desk-kit',
    name: 'Mug and Desk Kit',
    description: 'Box with mug, wood block, and small desk pieces.',
    price: 629,
    bulkPrice: 'From ₹490/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/03.jpg', '/images/catalog/eco-friendly/03-alt.jpg'],
    features: ['Mug', 'Wood accessories', 'Gift box'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-cork-notebook',
    name: 'Cork Notebook',
    description: 'Cork notebook with a pen and small card.',
    price: 719,
    bulkPrice: 'From ₹560/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/04.jpg', '/images/catalog/eco-friendly/04-alt.jpg'],
    features: ['Cork notebook', 'Pen', 'Card'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-cork-notebook-tumbler-set',
    name: 'Cork Notebook and Tumbler Set',
    description: 'Desk set with cork notebook, tumbler, pen, and card.',
    price: 809,
    bulkPrice: 'From ₹630/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/05.jpg', '/images/catalog/eco-friendly/05-alt.jpg'],
    features: ['Cork notebook', 'Tumbler', 'Pen'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-zip-tech-pouch',
    name: 'Zippered Tech Pouch',
    description: 'Open pouch with cables and small tech accessories.',
    price: 899,
    bulkPrice: 'From ₹700/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/06.jpg', '/images/catalog/eco-friendly/06-alt.jpg'],
    features: ['Zip pouch', 'Cables', 'Accessories'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-red-notebook-box',
    name: 'Red Notebook Gift Box',
    description: 'Box with red notebook, cork panel, and pen.',
    price: 989,
    bulkPrice: 'From ₹770/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/07.jpg', '/images/catalog/eco-friendly/07-alt.jpg'],
    features: ['Red notebook', 'Cork panel', 'Pen'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bamboo-board-bottle-set',
    name: 'Bamboo Board and Bottle Set',
    description: 'Bamboo board, bottle, and pen in a black box.',
    price: 1079,
    bulkPrice: 'From ₹840/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/08.jpg', '/images/catalog/eco-friendly/08-alt.jpg'],
    features: ['Bamboo board', 'Bottle', 'Pen'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-pen-and-tag-set',
    name: 'Pen and Tag Set',
    description: 'Pen with a round tag in a black box.',
    price: 1169,
    bulkPrice: 'From ₹910/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/09.jpg', '/images/catalog/eco-friendly/09-alt.jpg'],
    features: ['Pen', 'Round tag', 'Black box'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bamboo-bottle-mug-set',
    name: 'Bamboo Bottle and Mug Set',
    description: 'Bottle, mug, and bamboo pieces laid on kraft card.',
    price: 1259,
    bulkPrice: 'From ₹980/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/10.jpg', '/images/catalog/eco-friendly/10-alt.jpg'],
    features: ['Bottle', 'Mug', 'Bamboo pieces'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-spiral-notebook-set',
    name: 'Spiral Notebook Set',
    description: 'Tray with spiral notebook, bottle, and pen.',
    price: 1349,
    bulkPrice: 'From ₹1,050/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/11.jpg', '/images/catalog/eco-friendly/11-alt.jpg'],
    features: ['Spiral notebook', 'Bottle', 'Pen'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bamboo-desk-set',
    name: 'Bamboo Desk Set',
    description: 'Tray with bottle, wooden block, and notebook.',
    price: 1439,
    bulkPrice: 'From ₹1,120/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/12.jpg', '/images/catalog/eco-friendly/12-alt.jpg'],
    features: ['Bottle', 'Wood block', 'Notebook'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bamboo-journal-box',
    name: 'Bamboo Journal Box',
    description: 'Open box with bamboo board, notebook, and clips.',
    price: 1529,
    bulkPrice: 'From ₹1,190/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/13.jpg', '/images/catalog/eco-friendly/13-alt.jpg'],
    features: ['Bamboo board', 'Notebook', 'Clips'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-bottle-and-mug-box',
    name: 'Bottle and Mug Box',
    description: 'Open box with black bottle and mug.',
    price: 1619,
    bulkPrice: 'From ₹1,260/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/14.jpg', '/images/catalog/eco-friendly/14-alt.jpg'],
    features: ['Bottle', 'Mug', 'Gift box'],
  },
  {
    categorySlug: 'eco-friendly-gifting',
    slug: 'eco-black-bottle-trio-set',
    name: 'Black Bottle Trio Set',
    description: 'Bottles, mug, and notebook arranged with a box.',
    price: 1709,
    bulkPrice: 'From ₹1,330/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/15.jpg', '/images/catalog/eco-friendly/15-alt.jpg'],
    features: ['Bottles', 'Mug', 'Notebook'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-countertop-appliance',
    name: 'Countertop Appliance',
    description: 'Red countertop appliance shown with its retail box.',
    price: 899,
    bulkPrice: 'From ₹700/unit (25+ qty)',
    images: ['/images/catalog/tech/01.jpg', '/images/catalog/tech/01-alt.jpg'],
    features: ['Countertop appliance', 'Retail box'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-colour-brain-lights',
    name: 'Colour Brain Lights',
    description: 'Four small lights in white, red, green, and blue.',
    price: 1049,
    bulkPrice: 'From ₹820/unit (25+ qty)',
    images: ['/images/catalog/tech/02.jpg', '/images/catalog/tech/02-alt.jpg'],
    features: ['Set of four lights', 'Colour variants'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-cordless-stick-vacuum',
    name: 'Cordless Stick Vacuum',
    description: 'Cordless stick vacuum with spare parts laid out.',
    price: 1199,
    bulkPrice: 'From ₹940/unit (25+ qty)',
    images: ['/images/catalog/tech/03.jpg', '/images/catalog/tech/03-alt.jpg'],
    features: ['Stick vacuum', 'Spare parts'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-desk-fan',
    name: 'Desk Fan',
    description: 'White desk fan on a stand with a small remote.',
    price: 1349,
    bulkPrice: 'From ₹1,050/unit (25+ qty)',
    images: ['/images/catalog/tech/04.jpg', '/images/catalog/tech/04-alt.jpg'],
    features: ['Desk fan', 'Remote'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-portable-desk-fan',
    name: 'Portable Desk Fan',
    description: 'White portable fan shown with its box.',
    price: 1499,
    bulkPrice: 'From ₹1,170/unit (25+ qty)',
    images: ['/images/catalog/tech/05.jpg', '/images/catalog/tech/05-alt.jpg'],
    features: ['Portable fan', 'Box'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-portable-speaker',
    name: 'Portable Speaker',
    description: 'Black cylindrical speaker with a carry handle.',
    price: 1649,
    bulkPrice: 'From ₹1,290/unit (25+ qty)',
    images: ['/images/catalog/tech/06.jpg', '/images/catalog/tech/06-alt.jpg'],
    features: ['Portable speaker', 'Carry handle'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-handheld-massager',
    name: 'Handheld Massager',
    description: 'Silver handheld massager with box and cable.',
    price: 1799,
    bulkPrice: 'From ₹1,400/unit (25+ qty)',
    images: ['/images/catalog/tech/07.jpg', '/images/catalog/tech/07-alt.jpg'],
    features: ['Handheld massager', 'Cable'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-handheld-fan',
    name: 'Handheld Fan',
    description: 'Pink handheld fan with its box.',
    price: 1949,
    bulkPrice: 'From ₹1,520/unit (25+ qty)',
    images: ['/images/catalog/tech/08.jpg', '/images/catalog/tech/08-alt.jpg'],
    features: ['Handheld fan', 'Box'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-digital-alarm-clock',
    name: 'Digital Alarm Clock',
    description: 'Round digital clock with an LED time display.',
    price: 2099,
    bulkPrice: 'From ₹1,640/unit (25+ qty)',
    images: ['/images/catalog/tech/09.jpg', '/images/catalog/tech/09-alt.jpg'],
    features: ['Digital clock', 'LED display'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-desk-lamp-organiser',
    name: 'Desk Lamp Organiser',
    description: 'White lamp with a pen holder base.',
    price: 2249,
    bulkPrice: 'From ₹1,750/unit (25+ qty)',
    images: ['/images/catalog/tech/10.jpg', '/images/catalog/tech/10-alt.jpg'],
    features: ['Desk lamp', 'Pen holder'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-travel-tumbler',
    name: 'Travel Tumbler',
    description: 'Tall black tumbler with a lid.',
    price: 1099,
    bulkPrice: 'From ₹860/unit (25+ qty)',
    images: ['/images/catalog/tech/11.jpg', '/images/catalog/tech/11-alt.jpg'],
    features: ['Tumbler', 'Lid'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-portable-lantern',
    name: 'Portable Lantern',
    description: 'Small glowing lantern with a metal handle.',
    price: 1249,
    bulkPrice: 'From ₹970/unit (25+ qty)',
    images: ['/images/catalog/tech/12.jpg', '/images/catalog/tech/12-alt.jpg'],
    features: ['Portable lantern', 'Handle'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-retro-radio',
    name: 'Retro Radio',
    description: 'White tabletop radio with speaker grille and knobs.',
    price: 1399,
    bulkPrice: 'From ₹1,090/unit (25+ qty)',
    images: ['/images/catalog/tech/13.jpg', '/images/catalog/tech/13-alt.jpg'],
    features: ['Tabletop radio', 'Knobs'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-cylinder-lamp',
    name: 'Cylinder Lamp',
    description: 'Tall cylinder lamp with vertical slats.',
    price: 1549,
    bulkPrice: 'From ₹1,210/unit (25+ qty)',
    images: ['/images/catalog/tech/14.jpg', '/images/catalog/tech/14-alt.jpg'],
    features: ['Cylinder lamp', 'Slatted shade'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-desk-light-kit',
    name: 'Desk Light Kit',
    description: 'Lamps and desk tools laid on a dark surface.',
    price: 1699,
    bulkPrice: 'From ₹1,330/unit (25+ qty)',
    images: ['/images/catalog/tech/15.jpg', '/images/catalog/tech/15-alt.jpg'],
    features: ['Lamps', 'Desk tools'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-karaoke-speaker',
    name: 'Karaoke Speaker',
    description: 'Speaker screen with two handheld microphones.',
    price: 1849,
    bulkPrice: 'From ₹1,440/unit (25+ qty)',
    images: ['/images/catalog/tech/16.jpg', '/images/catalog/tech/16-alt.jpg'],
    features: ['Speaker', 'Two microphones'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-electric-kettle',
    name: 'Electric Kettle',
    description: 'Matte black electric kettle.',
    price: 1999,
    bulkPrice: 'From ₹1,560/unit (25+ qty)',
    images: ['/images/catalog/tech/17.jpg', '/images/catalog/tech/17-alt.jpg'],
    features: ['Electric kettle', 'Lid'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-wireless-earbuds-green',
    name: 'Wireless Earbuds — Green',
    description: 'Green charging case with a pair of earbuds.',
    price: 2149,
    bulkPrice: 'From ₹1,680/unit (25+ qty)',
    images: ['/images/catalog/tech/18.jpg', '/images/catalog/tech/18-alt.jpg'],
    features: ['Earbuds', 'Charging case'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-wireless-earbuds-duo',
    name: 'Wireless Earbuds — Black and Blue',
    description: 'Two open cases with black and light earbuds.',
    price: 2299,
    bulkPrice: 'From ₹1,790/unit (25+ qty)',
    images: ['/images/catalog/tech/19.jpg', '/images/catalog/tech/19-alt.jpg'],
    features: ['Two cases', 'Earbuds'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-wireless-earbuds-mint',
    name: 'Wireless Earbuds — Mint',
    description: 'Mint and white charging case with earbuds.',
    price: 2449,
    bulkPrice: 'From ₹1,910/unit (25+ qty)',
    images: ['/images/catalog/tech/20.jpg', '/images/catalog/tech/20-alt.jpg'],
    features: ['Earbuds', 'Charging case'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-neckband-earphones',
    name: 'Neckband Earphones',
    description: 'Dark neckband earphones with inline controls.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (25+ qty)',
    images: ['/images/catalog/tech/21.jpg', '/images/catalog/tech/21-alt.jpg'],
    features: ['Neckband', 'Inline control'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-navy-neckband',
    name: 'Navy Neckband',
    description: 'Navy neckband earphones.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (25+ qty)',
    images: ['/images/catalog/tech/22.jpg', '/images/catalog/tech/22-alt.jpg'],
    features: ['Neckband earphones'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-open-ear-headset',
    name: 'Open-Ear Headset',
    description: 'Headset worn over the ear.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (25+ qty)',
    images: ['/images/catalog/tech/23.jpg', '/images/catalog/tech/23-alt.jpg'],
    features: ['Headset'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-sunglasses',
    name: 'Sunglasses',
    description: 'Two pairs of dark sunglasses on models.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (25+ qty)',
    images: ['/images/catalog/tech/24.jpg', '/images/catalog/tech/24-alt.jpg'],
    features: ['Sunglasses'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-power-bank-beige',
    name: 'Power Bank — Beige',
    description: 'Beige power bank with a wrist loop.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (25+ qty)',
    images: ['/images/catalog/tech/25.jpg', '/images/catalog/tech/25-alt.jpg'],
    features: ['Power bank', 'Wrist loop'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-power-bank-blue',
    name: 'Power Bank — Blue',
    description: 'Blue power bank with a digital display.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (25+ qty)',
    images: ['/images/catalog/tech/26.jpg', '/images/catalog/tech/26-alt.jpg'],
    features: ['Power bank', 'Display'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-power-bank-grey',
    name: 'Power Bank — Grey',
    description: 'Grey power bank with a charge display.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (25+ qty)',
    images: ['/images/catalog/tech/27.jpg', '/images/catalog/tech/27-alt.jpg'],
    features: ['Power bank', 'Display'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-soundbar',
    name: 'Soundbar',
    description: 'Compact soundbar with front lights.',
    price: 2349,
    bulkPrice: 'From ₹1,830/unit (25+ qty)',
    images: ['/images/catalog/tech/28.jpg', '/images/catalog/tech/28-alt.jpg'],
    features: ['Soundbar'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-mesh-soundbar',
    name: 'Mesh Soundbar',
    description: 'Low soundbar with a mesh grille.',
    price: 2499,
    bulkPrice: 'From ₹1,950/unit (25+ qty)',
    images: ['/images/catalog/tech/29.jpg', '/images/catalog/tech/29-alt.jpg'],
    features: ['Soundbar', 'Mesh grille'],
  },
  {
    categorySlug: 'tech-gifts',
    slug: 'tech-soundbar-and-subwoofer',
    name: 'Soundbar and Subwoofer',
    description: 'Long soundbar paired with a subwoofer.',
    price: 2649,
    bulkPrice: 'From ₹2,070/unit (25+ qty)',
    images: ['/images/catalog/tech/30.jpg', '/images/catalog/tech/30-alt.jpg'],
    features: ['Soundbar', 'Subwoofer'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-patterned-bottle',
    name: 'Patterned Steel Bottle',
    description: 'Grey bottle with a cutwork sleeve and sip lid.',
    price: 349,
    bulkPrice: 'From ₹270/unit (50+ qty)',
    images: ['/images/catalog/drinkware/01.jpg', '/images/catalog/drinkware/01-alt.jpg'],
    features: ['Steel bottle', 'Sip lid'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-slim-black-bottle',
    name: 'Slim Black Bottle',
    description: 'Tall slim black bottle with a screw cap.',
    price: 389,
    bulkPrice: 'From ₹300/unit (50+ qty)',
    images: ['/images/catalog/drinkware/02.jpg', '/images/catalog/drinkware/02-alt.jpg'],
    features: ['Slim bottle', 'Screw cap'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-handled-tumbler-blue',
    name: 'Blue Handled Tumbler',
    description: 'Light blue tumbler with handle, straw, and lid.',
    price: 429,
    bulkPrice: 'From ₹330/unit (50+ qty)',
    images: ['/images/catalog/drinkware/03.jpg', '/images/catalog/drinkware/03-alt.jpg'],
    features: ['Handle', 'Straw lid'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-teal-sleeve-bottle',
    name: 'Teal Sleeve Bottle',
    description: 'Teal bottle with a patterned sleeve.',
    price: 469,
    bulkPrice: 'From ₹370/unit (50+ qty)',
    images: ['/images/catalog/drinkware/04.jpg', '/images/catalog/drinkware/04-alt.jpg'],
    features: ['Bottle', 'Sleeve'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-loop-cap-bottle',
    name: 'Loop-Cap Bottle',
    description: 'Black bottle with a green carry loop.',
    price: 509,
    bulkPrice: 'From ₹400/unit (50+ qty)',
    images: ['/images/catalog/drinkware/05.jpg', '/images/catalog/drinkware/05-alt.jpg'],
    features: ['Bottle', 'Carry loop'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-white-tumbler',
    name: 'White Tumbler',
    description: 'White tumbler with a steel rim.',
    price: 549,
    bulkPrice: 'From ₹430/unit (50+ qty)',
    images: ['/images/catalog/drinkware/06.jpg', '/images/catalog/drinkware/06-alt.jpg'],
    features: ['Tumbler', 'Steel rim'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-steel-bottle-trio',
    name: 'Steel Bottle Trio',
    description: 'Three bottles in black, navy, and white.',
    price: 589,
    bulkPrice: 'From ₹460/unit (50+ qty)',
    images: ['/images/catalog/drinkware/07.jpg', '/images/catalog/drinkware/07-alt.jpg'],
    features: ['Set of three bottles'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-silicone-coffee-cup',
    name: 'Silicone Coffee Cup',
    description: 'Cup with a blue silicone sleeve and lid.',
    price: 629,
    bulkPrice: 'From ₹490/unit (50+ qty)',
    images: ['/images/catalog/drinkware/08.jpg', '/images/catalog/drinkware/08-alt.jpg'],
    features: ['Silicone sleeve', 'Lid'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-slotted-cup-holder',
    name: 'Slotted Cup Holder',
    description: 'Grey holder with a clear cup insert.',
    price: 669,
    bulkPrice: 'From ₹520/unit (50+ qty)',
    images: ['/images/catalog/drinkware/09.jpg', '/images/catalog/drinkware/09-alt.jpg'],
    features: ['Holder', 'Cup insert'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'coffee-mug-cork-detail',
    name: 'Coffee Cup with Cork Sleeve',
    description: 'Black cup with a natural cork sleeve.',
    price: 709,
    bulkPrice: 'From ₹550/unit (50+ qty)',
    images: ['/images/catalog/drinkware/10.jpg', '/images/catalog/drinkware/10-alt.jpg'],
    features: ['Cork sleeve', 'Lid'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-silver-carry-bottle',
    name: 'Silver Carry Bottle',
    description: 'Silver bottle with a loop handle.',
    price: 749,
    bulkPrice: 'From ₹580/unit (50+ qty)',
    images: ['/images/catalog/drinkware/11.jpg', '/images/catalog/drinkware/11-alt.jpg'],
    features: ['Silver bottle', 'Loop handle'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-stacked-black-bottle',
    name: 'Stacked Black Bottle',
    description: 'Black bottle with a white band and two-part body.',
    price: 789,
    bulkPrice: 'From ₹620/unit (50+ qty)',
    images: ['/images/catalog/drinkware/12.jpg', '/images/catalog/drinkware/12-alt.jpg'],
    features: ['Two-part bottle', 'Cap'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-infuser-bottle',
    name: 'Infuser Bottle',
    description: 'Matte bottle shown with a loose infuser piece.',
    price: 829,
    bulkPrice: 'From ₹650/unit (50+ qty)',
    images: ['/images/catalog/drinkware/13.jpg', '/images/catalog/drinkware/13-alt.jpg'],
    features: ['Bottle', 'Infuser'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-navy-steel-bottle',
    name: 'Navy Steel Bottle',
    description: 'Navy bottle with a steel cap.',
    price: 869,
    bulkPrice: 'From ₹680/unit (50+ qty)',
    images: ['/images/catalog/drinkware/14.jpg', '/images/catalog/drinkware/14-alt.jpg'],
    features: ['Steel bottle', 'Steel cap'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-tumbler-sip-lid',
    name: 'Tumbler Sip Lid',
    description: 'Close view of a black sip lid.',
    price: 909,
    bulkPrice: 'From ₹710/unit (50+ qty)',
    images: ['/images/catalog/drinkware/15.jpg', '/images/catalog/drinkware/15-alt.jpg'],
    features: ['Sip lid'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-glass-panel-bottle',
    name: 'Glass Panel Bottle',
    description: 'Black bottle with clear glass panels.',
    price: 949,
    bulkPrice: 'From ₹740/unit (50+ qty)',
    images: ['/images/catalog/drinkware/16.jpg', '/images/catalog/drinkware/16-alt.jpg'],
    features: ['Glass panels', 'Carry loop'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-black-handled-tumbler',
    name: 'Black Handled Tumbler',
    description: 'Black tumbler with a top handle and steel rim.',
    price: 989,
    bulkPrice: 'From ₹770/unit (50+ qty)',
    images: ['/images/catalog/drinkware/17.jpg', '/images/catalog/drinkware/17-alt.jpg'],
    features: ['Handle', 'Steel rim'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-black-desk-mug',
    name: 'Black Desk Mug',
    description: 'Black mug with a side handle and steel rim.',
    price: 1029,
    bulkPrice: 'From ₹800/unit (50+ qty)',
    images: ['/images/catalog/drinkware/18.jpg', '/images/catalog/drinkware/18-alt.jpg'],
    features: ['Mug', 'Handle'],
  },
  {
    categorySlug: 'drinkware',
    slug: 'drinkware-white-biscuit-mug',
    name: 'White Biscuit Mug',
    description: 'White mug with a small side shelf.',
    price: 1069,
    bulkPrice: 'From ₹830/unit (50+ qty)',
    images: ['/images/catalog/drinkware/19.jpg', '/images/catalog/drinkware/19-alt.jpg'],
    features: ['Mug', 'Side shelf'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-star-crystal-set',
    name: 'Star Crystal Award Set',
    description: 'Three clear crystal awards with star detail.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (10+ qty)',
    images: ['/images/catalog/trophies/01.jpg', '/images/catalog/trophies/01-alt.jpg'],
    features: ['Set of three', 'Crystal', 'Star detail'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-stage-crystal-presentation',
    name: 'Stage Crystal Presentation',
    description: 'Crystal award being presented on a stage.',
    price: 1719,
    bulkPrice: 'From ₹1,340/unit (10+ qty)',
    images: ['/images/catalog/trophies/02.jpg', '/images/catalog/trophies/02-alt.jpg'],
    features: ['Crystal award', 'Stage presentation'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-hexagon-crystal-trio',
    name: 'Hexagon Crystal Trio',
    description: 'Three hexagonal crystal awards on black bases.',
    price: 1839,
    bulkPrice: 'From ₹1,430/unit (10+ qty)',
    images: ['/images/catalog/trophies/03.jpg', '/images/catalog/trophies/03-alt.jpg'],
    features: ['Three awards', 'Crystal'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-round-wood-award',
    name: 'Round Wood Award',
    description: 'Round wooden award with a metal plaque.',
    price: 1959,
    bulkPrice: 'From ₹1,530/unit (10+ qty)',
    images: ['/images/catalog/trophies/04.jpg', '/images/catalog/trophies/04-alt.jpg'],
    features: ['Wood base', 'Plaque'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-star-award-presentation',
    name: 'Star Award Presentation',
    description: 'Star-topped award presented on stage.',
    price: 2079,
    bulkPrice: 'From ₹1,620/unit (10+ qty)',
    images: ['/images/catalog/trophies/05.jpg', '/images/catalog/trophies/05-alt.jpg'],
    features: ['Star award'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-column-crystal-award',
    name: 'Column Crystal Award',
    description: 'Tall crystal award presented between two people.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (10+ qty)',
    images: ['/images/catalog/trophies/06.jpg', '/images/catalog/trophies/06-alt.jpg'],
    features: ['Column crystal'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-plaque-and-certificate',
    name: 'Plaque and Certificate',
    description: 'Award plaque held with a certificate.',
    price: 2319,
    bulkPrice: 'From ₹1,810/unit (10+ qty)',
    images: ['/images/catalog/trophies/07.jpg', '/images/catalog/trophies/07-alt.jpg'],
    features: ['Plaque', 'Certificate'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-gold-star-award',
    name: 'Gold Star Award',
    description: 'Gold star award on a dark base.',
    price: 2439,
    bulkPrice: 'From ₹1,900/unit (10+ qty)',
    images: ['/images/catalog/trophies/08.jpg', '/images/catalog/trophies/08-alt.jpg'],
    features: ['Star award', 'Base'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-star-trophy',
    name: 'Star Trophy',
    description: 'Star trophy presented on stage.',
    price: 2559,
    bulkPrice: 'From ₹2,000/unit (10+ qty)',
    images: ['/images/catalog/trophies/09.jpg', '/images/catalog/trophies/09-alt.jpg'],
    features: ['Star trophy'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-certificate-award',
    name: 'Certificate Award',
    description: 'Framed certificate award held on stage.',
    price: 2679,
    bulkPrice: 'From ₹2,090/unit (10+ qty)',
    images: ['/images/catalog/trophies/10.jpg', '/images/catalog/trophies/10-alt.jpg'],
    features: ['Certificate'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-cup-trophy',
    name: 'Cup Trophy',
    description: 'Cup-shaped trophy with a star emblem.',
    price: 2799,
    bulkPrice: 'From ₹2,180/unit (10+ qty)',
    images: ['/images/catalog/trophies/11.jpg', '/images/catalog/trophies/11-alt.jpg'],
    features: ['Trophy', 'Star emblem'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-white-plaque',
    name: 'White Plaque',
    description: 'White award plaque.',
    price: 2919,
    bulkPrice: 'From ₹2,280/unit (10+ qty)',
    images: ['/images/catalog/trophies/12.jpg', '/images/catalog/trophies/12-alt.jpg'],
    features: ['Plaque'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-blue-plaque',
    name: 'Blue Award Plaque',
    description: 'Blue plaque presented at a ceremony.',
    price: 3039,
    bulkPrice: 'From ₹2,370/unit (10+ qty)',
    images: ['/images/catalog/trophies/13.jpg', '/images/catalog/trophies/13-alt.jpg'],
    features: ['Plaque'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-spike-crystal',
    name: 'Spike Crystal Award',
    description: 'Clear pointed crystal award.',
    price: 3159,
    bulkPrice: 'From ₹2,460/unit (10+ qty)',
    images: ['/images/catalog/trophies/14.jpg', '/images/catalog/trophies/14-alt.jpg'],
    features: ['Crystal'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-crystal-cup',
    name: 'Crystal Cup Award',
    description: 'Cut crystal cup on a stage.',
    price: 3279,
    bulkPrice: 'From ₹2,560/unit (10+ qty)',
    images: ['/images/catalog/trophies/15.jpg', '/images/catalog/trophies/15-alt.jpg'],
    features: ['Crystal cup'],
  },
  {
    categorySlug: 'trophies-vouchers',
    slug: 'trophy-ceremony-crystal',
    name: 'Ceremony Crystal Award',
    description: 'Crystal award at a ceremony handshake.',
    price: 3399,
    bulkPrice: 'From ₹2,650/unit (10+ qty)',
    images: ['/images/catalog/trophies/16.jpg', '/images/catalog/trophies/16-alt.jpg'],
    features: ['Crystal award'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-conference-tech-pouch',
    name: 'Conference Tech Pouch',
    description: 'Zippered pouch with cables and small accessories.',
    price: 649,
    bulkPrice: 'From ₹510/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/06.jpg', '/images/catalog/eco-friendly/06-alt.jpg'],
    features: ['Zip pouch', 'Cables'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-conference-cork-notebook',
    name: 'Conference Cork Notebook',
    description: 'Cork notebook and pen suitable for a delegate kit.',
    price: 759,
    bulkPrice: 'From ₹590/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/04.jpg', '/images/catalog/eco-friendly/04-alt.jpg'],
    features: ['Cork notebook', 'Pen'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-delegate-desk-set',
    name: 'Delegate Desk Set',
    description: 'Notebook, tumbler, and pen laid out as a desk kit.',
    price: 869,
    bulkPrice: 'From ₹680/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/05.jpg', '/images/catalog/eco-friendly/05-alt.jpg'],
    features: ['Notebook', 'Tumbler', 'Pen'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-delegate-spiral-notebook',
    name: 'Delegate Spiral Notebook Set',
    description: 'Spiral notebook, bottle, and pen in a tray.',
    price: 979,
    bulkPrice: 'From ₹760/unit (50+ qty)',
    images: ['/images/catalog/eco-friendly/11.jpg', '/images/catalog/eco-friendly/11-alt.jpg'],
    features: ['Spiral notebook', 'Bottle', 'Pen'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-event-slim-bottle',
    name: 'Event Slim Bottle',
    description: 'Slim black bottle for event gifting.',
    price: 1089,
    bulkPrice: 'From ₹850/unit (50+ qty)',
    images: ['/images/catalog/drinkware/02.jpg', '/images/catalog/drinkware/02-alt.jpg'],
    features: ['Slim bottle', 'Cap'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-event-white-tumbler',
    name: 'Event White Tumbler',
    description: 'White tumbler for conference kits.',
    price: 1199,
    bulkPrice: 'From ₹940/unit (50+ qty)',
    images: ['/images/catalog/drinkware/06.jpg', '/images/catalog/drinkware/06-alt.jpg'],
    features: ['Tumbler', 'Steel rim'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-event-coffee-cup',
    name: 'Event Coffee Cup',
    description: 'Lidded coffee cup with a blue sleeve.',
    price: 1309,
    bulkPrice: 'From ₹1,020/unit (50+ qty)',
    images: ['/images/catalog/drinkware/08.jpg', '/images/catalog/drinkware/08-alt.jpg'],
    features: ['Cup', 'Sleeve', 'Lid'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-event-desk-lamp',
    name: 'Event Desk Lamp',
    description: 'Desk lamp with a pen holder.',
    price: 1419,
    bulkPrice: 'From ₹1,110/unit (50+ qty)',
    images: ['/images/catalog/tech/10.jpg', '/images/catalog/tech/10-alt.jpg'],
    features: ['Lamp', 'Pen holder'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-speaker-desk-light-kit',
    name: 'Speaker Desk Light Kit',
    description: 'Desk lights and tools for a speaker gift.',
    price: 1529,
    bulkPrice: 'From ₹1,190/unit (50+ qty)',
    images: ['/images/catalog/tech/15.jpg', '/images/catalog/tech/15-alt.jpg'],
    features: ['Desk lights', 'Tools'],
  },
  {
    categorySlug: 'event-conference-gifting',
    slug: 'event-event-notebook-flask',
    name: 'Event Notebook and Flask Set',
    description: 'Notebook, mug, and flask in a white box.',
    price: 1639,
    bulkPrice: 'From ₹1,280/unit (50+ qty)',
    images: ['/images/catalog/corporate-listing/download-15.jpg', '/images/catalog/corporate-listing/download-15-alt.jpg'],
    features: ['Notebook', 'Mug', 'Flask'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-mandala-hex-box',
    name: 'Mandala Hex Gift Box',
    description: 'Corporate Diwali gift box: mandala hex gift box.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (50+ qty)',
    images: ['/images/catalog/diwali/01.jpg', '/images/catalog/diwali/01-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-paired-hex-boxes',
    name: 'Paired Hex Gift Boxes',
    description: 'Corporate Diwali gift box: paired hex gift boxes.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (50+ qty)',
    images: ['/images/catalog/diwali/02.jpg', '/images/catalog/diwali/02-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-floral-hex-box',
    name: 'Floral Hex Gift Box',
    description: 'Corporate Diwali gift box: floral hex gift box.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (50+ qty)',
    images: ['/images/catalog/diwali/03.jpg', '/images/catalog/diwali/03-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-hex-box-set',
    name: 'Hex Gift Box Set',
    description: 'Corporate Diwali gift box: hex gift box set.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (50+ qty)',
    images: ['/images/catalog/diwali/04.jpg', '/images/catalog/diwali/04-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-jar-gift-box',
    name: 'Diwali Jar Gift Box',
    description: 'Corporate Diwali gift box: diwali jar gift box.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (50+ qty)',
    images: ['/images/catalog/diwali/05.jpg', '/images/catalog/diwali/05-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-open-tray-box',
    name: 'Open Tray Gift Box',
    description: 'Corporate Diwali gift box: open tray gift box.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (50+ qty)',
    images: ['/images/catalog/diwali/06.jpg', '/images/catalog/diwali/06-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-navy-mini-hamper',
    name: 'Navy Mini Hamper',
    description: 'Corporate Diwali gift box: navy mini hamper.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (50+ qty)',
    images: ['/images/catalog/diwali/07.jpg', '/images/catalog/diwali/07-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-green-temple-box',
    name: 'Green Temple Gift Box',
    description: 'Corporate Diwali gift box: green temple gift box.',
    price: 2349,
    bulkPrice: 'From ₹1,830/unit (50+ qty)',
    images: ['/images/catalog/diwali/08.jpg', '/images/catalog/diwali/08-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-diwali-story-hamper',
    name: 'Diwali Story Hamper',
    description: 'Corporate Diwali gift box: diwali story hamper.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (50+ qty)',
    images: ['/images/catalog/diwali/09.jpg', '/images/catalog/diwali/09-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-red-assortment-box',
    name: 'Red Assortment Box',
    description: 'Corporate Diwali gift box: red assortment box.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (50+ qty)',
    images: ['/images/catalog/diwali/10.jpg', '/images/catalog/diwali/10-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-brush-gift-box',
    name: 'Paintbrush Gift Box',
    description: 'Corporate Diwali gift box: paintbrush gift box.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (50+ qty)',
    images: ['/images/catalog/diwali/11.jpg', '/images/catalog/diwali/11-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-assorted-open-hamper',
    name: 'Assorted Open Hamper',
    description: 'Corporate Diwali gift box: assorted open hamper.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (50+ qty)',
    images: ['/images/catalog/diwali/12.jpg', '/images/catalog/diwali/12-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-yellow-diwali-box',
    name: 'Yellow Diwali Box',
    description: 'Corporate Diwali gift box: yellow diwali box.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (50+ qty)',
    images: ['/images/catalog/diwali/13.jpg', '/images/catalog/diwali/13-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-tall-green-box',
    name: 'Tall Green Gift Box',
    description: 'Corporate Diwali gift box: tall green gift box.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (50+ qty)',
    images: ['/images/catalog/diwali/14.jpg', '/images/catalog/diwali/14-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-wood-lid-hamper',
    name: 'Wooden Lid Hamper',
    description: 'Corporate Diwali gift box: wooden lid hamper.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (50+ qty)',
    images: ['/images/catalog/diwali/15.jpg', '/images/catalog/diwali/15-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-jar-assortment-box',
    name: 'Jar Assortment Box',
    description: 'Corporate Diwali gift box: jar assortment box.',
    price: 2349,
    bulkPrice: 'From ₹1,830/unit (50+ qty)',
    images: ['/images/catalog/diwali/16.jpg', '/images/catalog/diwali/16-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-purple-diwali-box',
    name: 'Purple Diwali Box',
    description: 'Corporate Diwali gift box: purple diwali box.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (50+ qty)',
    images: ['/images/catalog/diwali/17.jpg', '/images/catalog/diwali/17-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-floral-open-hamper',
    name: 'Floral Open Hamper',
    description: 'Corporate Diwali gift box: floral open hamper.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (50+ qty)',
    images: ['/images/catalog/diwali/18.jpg', '/images/catalog/diwali/18-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-purple-jar-box',
    name: 'Purple Jar Box',
    description: 'Corporate Diwali gift box: purple jar box.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (50+ qty)',
    images: ['/images/catalog/diwali/19.jpg', '/images/catalog/diwali/19-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-green-arch-box',
    name: 'Green Arch Gift Box',
    description: 'Corporate Diwali gift box: green arch gift box.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (50+ qty)',
    images: ['/images/catalog/diwali/20.jpg', '/images/catalog/diwali/20-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-blue-lid-hamper',
    name: 'Blue Lid Hamper',
    description: 'Corporate Diwali gift box: blue lid hamper.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (50+ qty)',
    images: ['/images/catalog/diwali/21.jpg', '/images/catalog/diwali/21-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-drawer-snack-box',
    name: 'Drawer Snack Box',
    description: 'Corporate Diwali gift box: drawer snack box.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (50+ qty)',
    images: ['/images/catalog/diwali/22.jpg', '/images/catalog/diwali/22-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-sweets-drawer-box',
    name: 'Sweets Drawer Box',
    description: 'Corporate Diwali gift box: sweets drawer box.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (50+ qty)',
    images: ['/images/catalog/diwali/23.jpg', '/images/catalog/diwali/23-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-red-festive-box',
    name: 'Red Festive Box',
    description: 'Corporate Diwali gift box: red festive box.',
    price: 2349,
    bulkPrice: 'From ₹1,830/unit (50+ qty)',
    images: ['/images/catalog/diwali/24.jpg', '/images/catalog/diwali/24-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-cream-hamper',
    name: 'Cream Festive Hamper',
    description: 'Corporate Diwali gift box: cream festive hamper.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (50+ qty)',
    images: ['/images/catalog/diwali/25.jpg', '/images/catalog/diwali/25-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-green-jar-hamper',
    name: 'Green Jar Hamper',
    description: 'Corporate Diwali gift box: green jar hamper.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (50+ qty)',
    images: ['/images/catalog/diwali/26.jpg', '/images/catalog/diwali/26-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-pink-jar-box',
    name: 'Pink Jar Box',
    description: 'Corporate Diwali gift box: pink jar box.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (50+ qty)',
    images: ['/images/catalog/diwali/27.jpg', '/images/catalog/diwali/27-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-green-sweets-box',
    name: 'Green Sweets Box',
    description: 'Corporate Diwali gift box: green sweets box.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (50+ qty)',
    images: ['/images/catalog/diwali/28.jpg', '/images/catalog/diwali/28-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-pink-stack-box',
    name: 'Pink Stack Box',
    description: 'Corporate Diwali gift box: pink stack box.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (50+ qty)',
    images: ['/images/catalog/diwali/29.jpg', '/images/catalog/diwali/29-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-twin-jar-set',
    name: 'Twin Jar Gift Set',
    description: 'Corporate Diwali gift box: twin jar gift set.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (50+ qty)',
    images: ['/images/catalog/diwali/30.jpg', '/images/catalog/diwali/30-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-open-sweet-box',
    name: 'Open Sweet Box',
    description: 'Corporate Diwali gift box: open sweet box.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (50+ qty)',
    images: ['/images/catalog/diwali/31.jpg', '/images/catalog/diwali/31-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-green-open-hamper',
    name: 'Green Open Hamper',
    description: 'Corporate Diwali gift box: green open hamper.',
    price: 2349,
    bulkPrice: 'From ₹1,830/unit (50+ qty)',
    images: ['/images/catalog/diwali/32.jpg', '/images/catalog/diwali/32-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-blue-diwali-hamper',
    name: 'Blue Diwali Hamper',
    description: 'Corporate Diwali gift box: blue diwali hamper.',
    price: 1299,
    bulkPrice: 'From ₹1,010/unit (50+ qty)',
    images: ['/images/catalog/diwali/33.jpg', '/images/catalog/diwali/33-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-purple-open-box',
    name: 'Purple Open Box',
    description: 'Corporate Diwali gift box: purple open box.',
    price: 1449,
    bulkPrice: 'From ₹1,130/unit (50+ qty)',
    images: ['/images/catalog/diwali/34.jpg', '/images/catalog/diwali/34-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-drawer-chest',
    name: 'Festive Drawer Chest',
    description: 'Corporate Diwali gift box: festive drawer chest.',
    price: 1599,
    bulkPrice: 'From ₹1,250/unit (50+ qty)',
    images: ['/images/catalog/diwali/35.jpg', '/images/catalog/diwali/35-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-happy-diwali-hex',
    name: 'Happy Diwali Hex Box',
    description: 'Corporate Diwali gift box: happy diwali hex box.',
    price: 1749,
    bulkPrice: 'From ₹1,360/unit (50+ qty)',
    images: ['/images/catalog/diwali/36.jpg', '/images/catalog/diwali/36-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-tall-box-pair',
    name: 'Tall Festive Box Pair',
    description: 'Corporate Diwali gift box: tall festive box pair.',
    price: 1899,
    bulkPrice: 'From ₹1,480/unit (50+ qty)',
    images: ['/images/catalog/diwali/37.jpg', '/images/catalog/diwali/37-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-pink-blue-box-set',
    name: 'Pink and Blue Box Set',
    description: 'Corporate Diwali gift box: pink and blue box set.',
    price: 2049,
    bulkPrice: 'From ₹1,600/unit (50+ qty)',
    images: ['/images/catalog/diwali/38.jpg', '/images/catalog/diwali/38-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
  {
    categorySlug: 'festive-gifts',
    slug: 'diwali-long-sweet-box',
    name: 'Long Sweet Box',
    description: 'Corporate Diwali gift box: long sweet box.',
    price: 2199,
    bulkPrice: 'From ₹1,720/unit (50+ qty)',
    images: ['/images/catalog/diwali/39.jpg', '/images/catalog/diwali/39-alt.jpg'],
    features: ['Festive gift box', 'Packed assortment', 'Gift-ready presentation'],
  },
];

export const ECO_CATALOG_FEATURED_SLUGS = [
  'eco-bamboo-bottle-journal-box',
  'eco-black-journal-bottle-box',
  'eco-mug-desk-kit',
  'eco-cork-notebook',
  'eco-cork-notebook-tumbler-set',
  'eco-zip-tech-pouch',
] as const;

export const DIWALI_HOME_SLUGS = [
  'diwali-mandala-hex-box',
  'diwali-jar-gift-box',
  'diwali-green-temple-box',
  'diwali-yellow-diwali-box',
  'diwali-blue-lid-hamper',
  'diwali-twin-jar-set',
  'diwali-happy-diwali-hex',
  'diwali-long-sweet-box',
  'diwali-navy-mini-hamper',
  'diwali-floral-open-hamper',
  'diwali-drawer-chest',
  'diwali-pink-blue-box-set',
] as const;
